"""Layer 3: the required local-AI component. Triages false positives,
explains flagged findings in plain English, and writes corrected code — all
via a local Ollama model. See CLAUDE.md in this folder for the full spec.
"""

from __future__ import annotations

import ast
import json
import os
import re
import textwrap
from functools import lru_cache
from pathlib import Path

import ollama

from vericode.llm_explain import evidence
from vericode.shared.finding import Finding

# 1.5b: 6/7 verdicts at ~8s per finding on a CPU-only laptop in our benchmark.
PRIMARY_MODEL = "qwen2.5-coder:1.5b"
FALLBACK_MODEL = "qwen2.5-coder:3b"
# Every outage note starts with this so the gate can match it without parsing the cause.
LLM_UNAVAILABLE_PREFIX = "LLM unavailable, showing static check only"
OTHER_MODELS = ("qwen2.5-coder:7b",)
MAX_ANSWER_TOKENS = 200
TIMEOUT_SECONDS = 30.0  # 1.5b took 11-20s per finding on a CPU-only laptop
MAX_AI_FINDINGS = 3
KEEP_ALIVE = "30m"
CONTEXT_LINES = 3  # 5 lines cost ~4s more per finding on CPU with no accuracy gain
SEVERITY_RANK = {"high": 0, "medium": 1, "low": 2}

# Fixed text first, the finding last: Ollama reuses its work on an identical
# prefix, so every finding after the first skips reading these instructions.
# The examples are what got the 1.5b model to write fixes as code, not advice.
PROMPT_PREFIX = """You review findings from a security scanner.
Is this a real risk here, or a false alarm? A false alarm means no attacker or outside input can control it, or the value is a placeholder.
Answer in JSON. "reason": at most 25 words. "fix": only the corrected line(s) of code, empty if it's a false alarm. Never repeat secret values; read them from environment variables.

Example 1
Flagged: os.system() with a dynamic value
Static analysis found: Outside input reaches this call: `name` comes from input() (user input).
> 3: os.system("echo " + name)
Answer: {"reason": "User input reaches the shell, so an attacker can run commands.", "is_real_risk": true, "fix": "subprocess.run([\"echo\", name], check=True)"}

Example 2
Flagged: hardcoded API key
Static analysis found: The value has the shape of a real credential, not a placeholder.
> 1: STRIPE_KEY = "<REDACTED>"
Answer: {"reason": "A real key committed to Git leaks to anyone with the repo.", "is_real_risk": true, "fix": "STRIPE_KEY = os.environ[\"STRIPE_KEY\"]"}

Example 3
Flagged: os.system() with a dynamic value
Static analysis found: Only values generated by the program reach this call: time.time() (generated by the program).
> 5: os.system("touch log-" + str(time.time()))
Answer: {"reason": "Only a timestamp the program creates reaches the shell; no outside input.", "is_real_risk": false, "fix": ""}

Example 4
Flagged: 3 of 3 similar @app.post handlers call require_admin(user) before acting; reset_password doesn't.
> 8: def reset_password(user_id, user):
Answer: {"reason": "Every other handler checks the caller first; without it, any user can reset anyone's password.", "is_real_risk": true, "fix": "require_admin(user)"}

Now the real finding:
"""

FINDING_TEMPLATE = """A security scanner flagged line {line} of {file}:
{message}
{evidence}Code (">" marks the flagged line; secrets are replaced with {redacted}):
{code_context}"""

# Field order matters: with the verdict first, small models answered before
# reasoning and their verdicts contradicted their own reasons.
ANSWER_SCHEMA = {
    "type": "object",
    "properties": {
        "reason": {"type": "string"},
        "is_real_risk": {"type": "boolean"},
        "fix": {"type": "string"},
    },
    "required": ["reason", "is_real_risk", "fix"],
}

_JSON_OBJECT = re.compile(r"\{.*\}", re.DOTALL)

REDACTED = "<REDACTED>"
# Well-known token shapes, redacted wherever they appear.
_TOKEN_PATTERNS = [
    re.compile(r"-----BEGIN [A-Z ]*PRIVATE KEY-----.*?-----END [A-Z ]*PRIVATE KEY-----", re.DOTALL),
    re.compile(r"\bxox[abposr]-[A-Za-z0-9-]{8,}"),            # Slack
    re.compile(r"\bAKIA[0-9A-Z]{16}\b"),                      # AWS access key id
    re.compile(r"\bgh[pousr]_[A-Za-z0-9]{20,}"),               # GitHub
    re.compile(r"\bsk-[A-Za-z0-9_-]{16,}"),                    # OpenAI-style
    re.compile(r"\bAIza[0-9A-Za-z_-]{30,}"),                   # Google API key
    re.compile(r"(?i)\b(bearer\s+)[A-Za-z0-9._~+/=-]{16,}"),   # auth headers
]
# name = "value" where the name looks secret-ish: keep the name, blank the value.
_SECRET_ASSIGNMENT = re.compile(
    r"""(?ix)
    ([\w.-]*(?:secret|token|passw(?:or)?d|pwd|api[_-]?key|auth|credential|private[_-]?key)[\w.-]*
    ["']?\s*[:=]\s*)
    (["'])([^"'\n]{4,})\2
    """
)


def redact(text: str) -> str:
    """Blank secret values so they never reach the model or the report."""
    for pattern in _TOKEN_PATTERNS:
        text = pattern.sub(
            lambda m: (m.group(1) + REDACTED) if m.groups() else REDACTED, text
        )

    def blank(m: re.Match) -> str:
        if m.group(3) == REDACTED:
            return m.group(0)
        return f"{m.group(1)}{m.group(2)}{REDACTED}{m.group(2)}"

    return _SECRET_ASSIGNMENT.sub(blank, text)


def build_code_context(file: str, line: int, radius: int = CONTEXT_LINES) -> str:
    """Flagged line plus `radius` lines either side, numbered, marked with '>'.
    Returns a placeholder if the file can't be read."""
    try:
        lines = Path(file).read_text(encoding="utf-8", errors="replace").splitlines()
    except OSError:
        return "(source unavailable)"
    start = max(line - 1 - radius, 0)
    end = min(line + radius, len(lines))
    return "\n".join(
        f"{'>' if i + 1 == line else ' '} {i + 1}: {lines[i]}" for i in range(start, end)
    )


def _env_number(name: str, default: float, cast=float):
    try:
        value = cast(os.environ.get(name, default))
    except ValueError:
        return default
    return value if value > 0 else default


def timeout_seconds() -> float:
    """VERICODE_TIMEOUT override; CPU-only laptops need more than the default."""
    return _env_number("VERICODE_TIMEOUT", TIMEOUT_SECONDS)


def max_ai_findings() -> int:
    """VERICODE_MAX_AI_FINDINGS override; caps LLM calls per commit."""
    return _env_number("VERICODE_MAX_AI_FINDINGS", MAX_AI_FINDINGS, int)


def _client() -> ollama.Client:
    return ollama.Client(timeout=timeout_seconds())


@lru_cache(maxsize=1)
def pick_model() -> str:
    """VERICODE_MODEL override, else the first pulled of 1.5b, 3b, 7b.
    Raises RuntimeError when no usable model is installed."""
    override = os.environ.get("VERICODE_MODEL")
    if override:
        return override
    installed = {m.model for m in _client().list().models}
    for name in (PRIMARY_MODEL, FALLBACK_MODEL, *OTHER_MODELS):
        if name in installed:
            return name
    raise RuntimeError(
        f"no model installed; run `ollama pull {PRIMARY_MODEL}` (or {FALLBACK_MODEL})"
    )


def _chat(prompt: str) -> str:
    """Single local LLM call. Isolated so tests can mock it."""
    response = _client().chat(
        model=pick_model(),
        messages=[{"role": "user", "content": prompt}],
        format=ANSWER_SCHEMA,
        # otherwise ollama unloads the model after ~5 min idle and the next
        # commit waits for a multi-GB reload
        keep_alive=os.environ.get("VERICODE_KEEP_ALIVE", KEEP_ALIVE),
        options={"temperature": 0, "num_predict": MAX_ANSWER_TOKENS},
    )
    return response.message.content or ""


def _as_bool(value) -> bool | None:
    if isinstance(value, bool):
        return value
    if isinstance(value, str):
        v = value.strip().lower()
        if v in ("true", "yes"):
            return True
        if v in ("false", "no"):
            return False
    return None


def parse_response(raw: str) -> dict:
    """Parse model output into the four fields. Falls back to treating raw
    text as the explanation (is_real_risk=None) when JSON is unusable."""
    data = None
    for candidate in (raw, (_JSON_OBJECT.search(raw) or [None])[0] if raw else None):
        if not candidate:
            continue
        try:
            parsed = json.loads(candidate)
        except json.JSONDecodeError:
            continue
        if isinstance(parsed, dict):
            data = parsed
            break

    if data is None:
        text = raw.strip()
        return {
            "is_real_risk": None,
            "risk_reasoning": None,
            "explanation": text or "LLM returned an empty response.",
            "fixed_code": None,
        }

    def text_or_none(key: str) -> str | None:
        v = data.get(key)
        return None if v is None else str(v)

    reason = text_or_none("reason") or text_or_none("risk_reasoning")
    fix = text_or_none("fix") or text_or_none("fixed_code")
    return {
        "is_real_risk": _as_bool(data.get("is_real_risk")),
        "risk_reasoning": reason,
        "explanation": text_or_none("explanation") or reason,
        "fixed_code": fix or None,
    }


def _is_timeout(exc: Exception) -> bool:
    if isinstance(exc, TimeoutError):
        return True
    return any(cls.__name__ == "TimeoutException" for cls in type(exc).__mro__)


def _unavailable_detail(exc: Exception) -> str:
    """A short cause with no URL and no traceback. The setting name is VERICODE_TIMEOUT."""
    if isinstance(exc, ConnectionError) or type(exc).__name__ == "ConnectError":
        return "Local AI is off. Start it with: ollama serve"
    missing_model = (
        isinstance(exc, ollama.ResponseError) and getattr(exc, "status_code", None) == 404
    ) or (isinstance(exc, RuntimeError) and "no model installed" in str(exc))
    if missing_model:
        return f"Model not found. Run: ollama pull {PRIMARY_MODEL}"
    if _is_timeout(exc):
        return "Local AI took too long. Try a smaller model or raise VERICODE_TIMEOUT"
    return f"Local AI failed ({type(exc).__name__}). Showing static checks only."


def repair_code(code: str | None) -> str | None:
    """Small models sometimes leave one stray quote in otherwise valid code
    (`host'],` for `host],`). If deleting a single quote makes the fix parse,
    use that; anything else, including prose fixes, is returned unchanged."""
    if not code:
        return code
    def parses(text: str) -> bool:
        try:
            ast.parse(textwrap.dedent(text))
            return True
        except SyntaxError:
            return False
    if parses(code):
        return code
    # From the end: deleting an earlier quote can also parse, by merging
    # strings ('1', host' -> '1, host').
    for i in reversed(range(len(code))):
        if code[i] in "'\"" and parses(candidate := code[:i] + code[i + 1:]):
            return candidate
    return code


def _enrich_one(finding: Finding) -> None:
    facts = evidence.gather(finding)
    prompt = PROMPT_PREFIX + FINDING_TEMPLATE.format(
        message=redact(finding.message),
        file=finding.file,
        line=finding.line,
        evidence=f"Static analysis found: {redact(facts.text)}\n" if facts.text else "",
        code_context=redact(build_code_context(finding.file, finding.line)),
        redacted=REDACTED,
    )
    try:
        fields = parse_response(_chat(prompt))
    except Exception as exc:  # timeout, connection refused, missing model, ...
        finding.explanation = f"{LLM_UNAVAILABLE_PREFIX} ({_unavailable_detail(exc)})"
        return

    # Redact again on the way out: the model may echo or hallucinate a secret.
    clean = {k: (redact(v) if isinstance(v, str) else v) for k, v in fields.items()}
    finding.is_real_risk = clean["is_real_risk"]
    finding.risk_reasoning = clean["risk_reasoning"]
    finding.explanation = clean["explanation"]
    finding.fixed_code = repair_code(clean["fixed_code"])
    if finding.layer == "consistency":
        # the layer already names the exact missing call; the model tends to copy
        # the prompt's example guard instead
        finding.fixed_code = None
    if finding.is_real_risk is False:
        if facts.supports_dismissal:
            finding.severity = "low"
        else:
            # Small models sometimes call a real secret a false alarm; without
            # static evidence backing that up, the finding keeps blocking.
            finding.is_real_risk = None
            finding.explanation = (
                "The local AI thinks this may be a false alarm, but nothing in the code "
                f"confirms it, so it still counts. AI's reason: {finding.risk_reasoning}"
            )


def enrich(findings: list[Finding]) -> list[Finding]:
    """Call the local LLM only on the given (already-flagged) findings, fill
    in is_real_risk / risk_reasoning / explanation / fixed_code, and
    downgrade severity when is_real_risk is False instead of dropping it.
    Never raises: on LLM failure the finding is left as-is with a note in
    `explanation` (is_real_risk stays None so the gate still treats it as real).

    Import findings are never sent (Layer 1 is definitive for them). Of the
    rest, only the most severe max_ai_findings() go to the LLM, to keep the
    commit fast; the others keep is_real_risk=None, so the gate still treats
    them as real. Returned in the original order.
    """
    # Layer 1's verdict on an import is final (the AI may never clear it) and its
    # "Did you mean" beats a model-written fix, so a model call would only cost time.
    reviewable = [f for f in findings if f.layer != "import_check"]
    ranked = sorted(reviewable, key=lambda f: SEVERITY_RANK.get(f.severity, len(SEVERITY_RANK)))
    limit = max_ai_findings()
    for finding in ranked[:limit]:
        _enrich_one(finding)
    for finding in ranked[limit:]:
        finding.explanation = (
            f"Not reviewed by the local AI (limit of {limit} per commit; "
            f"set VERICODE_MAX_AI_FINDINGS to raise it)."
        )
    return findings


WARM_UP_FINDING = """A security scanner flagged line 1 of warm_up.py:
Warm-up request, no real finding.
Code (">" marks the flagged line; secrets are replaced with <REDACTED>):
> 1: pass"""


def warm_up() -> str | None:
    """Load the model and let Ollama cache PROMPT_PREFIX, so the first real
    finding doesn't pay for either. Returns the model name, or None if the
    local AI isn't reachable. Never raises."""
    try:
        model = pick_model()
        _client().chat(
            model=model,
            messages=[{"role": "user", "content": PROMPT_PREFIX + WARM_UP_FINDING}],
            keep_alive=os.environ.get("VERICODE_KEEP_ALIVE", KEEP_ALIVE),
            options={"temperature": 0, "num_predict": 1},
        )
        return model
    except Exception:
        return None
