import pytest

from vericode.llm_explain.evidence import gather
from vericode.shared.finding import Finding


def facts(tmp_path, source, line, layer="security_scan"):
    path = tmp_path / "app.py"
    path.write_text(source)
    return gather(Finding(layer=layer, file=str(path), line=line, severity="high", message="flagged"))


def test_command_line_input_through_a_function_parameter(tmp_path):
    src = "import os\nimport sys\n\ndef check(host):\n    os.system('ping ' + host)\n\ncheck(sys.argv[1])\n"
    ev = facts(tmp_path, src, 5)
    assert "sys.argv" in ev.text and "command-line input" in ev.text
    assert ev.supports_dismissal is False


def test_web_request_input(tmp_path):
    src = "import os\nfrom flask import request\n\ndef ping():\n    host = request.args['host']\n    os.system('ping ' + host)\n"
    ev = facts(tmp_path, src, 6)
    assert "web request input" in ev.text
    assert ev.supports_dismissal is False


def test_program_generated_value_can_be_dismissed(tmp_path):
    src = "import os\nfrom datetime import date\n\nos.system('cp a b-' + date.today().isoformat())\n"
    ev = facts(tmp_path, src, 4)
    assert "generated by the program" in ev.text
    assert ev.supports_dismissal is True


@pytest.mark.parametrize("call", [
    "os.system('clear')",
    "subprocess.run('git status', shell=True)",
])
def test_fixed_command_can_be_dismissed(tmp_path, call):
    ev = facts(tmp_path, f"import os\nimport subprocess\n{call}\n", 3)
    assert ev.text == "The command is a fixed value with no variables."
    assert ev.supports_dismissal is True


def test_unknown_origin_is_not_dismissable(tmp_path):
    src = "import os\nfrom helpers import build_cmd\n\nos.system(build_cmd())\n"
    ev = facts(tmp_path, src, 4)
    assert ev.supports_dismissal is False


def test_f_string_with_input(tmp_path):
    src = "import os\nname = input()\nos.system(f'echo {name}')\n"
    ev = facts(tmp_path, src, 3)
    assert "user input" in ev.text
    assert ev.supports_dismissal is False


@pytest.mark.parametrize("value", ["your-api-key-here", "changeme", "<YOUR_TOKEN>", "xxx-example"])
def test_placeholder_secret_can_be_dismissed(tmp_path, value):
    ev = facts(tmp_path, f'API_KEY = "{value}"\n', 1)
    assert ev.supports_dismissal is True


def _fake_token(prefix: str, body: str) -> str:
    return prefix + body


def test_real_looking_secret_is_not_dismissable_and_value_not_echoed(tmp_path):
    secret = _fake_token(
        "sk-",
        "9f8a7b6c5d4e3f2a1b0c",
    )
    ev = facts(tmp_path, 'API_KEY = "' + secret + '"\n', 1)
    assert ev.supports_dismissal is False
    assert _fake_token("sk-", "9f8a") not in ev.text


def test_fake_import_is_never_dismissable(tmp_path):
    ev = facts(tmp_path, "import markdown_pdf_export\n", 1, layer="import_check")
    assert ev.supports_dismissal is False


def test_missing_or_broken_file_never_raises(tmp_path):
    missing = gather(Finding(layer="security_scan", file=str(tmp_path / "nope.py"), line=1, severity="high", message="x"))
    assert missing.supports_dismissal is False
    broken = facts(tmp_path, "def broken(:\n", 1)
    assert broken.supports_dismissal is False
